// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ERC721A__IERC721Receiver$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ERC721A__IERC721Receiver",
  "sourceName": "erc721a/contracts/ERC721A.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "operator",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "tokenId",
          "type": "uint256"
        },
        {
          "internalType": "bytes",
          "name": "data",
          "type": "bytes"
        }
      ],
      "name": "onERC721Received",
      "outputs": [
        {
          "internalType": "bytes4",
          "name": "",
          "type": "bytes4"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ERC721A__IERC721Receiver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>>;
  export function deployContract(
    contractName: "erc721a/contracts/ERC721A.sol:ERC721A__IERC721Receiver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ERC721A__IERC721Receiver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "erc721a/contracts/ERC721A.sol:ERC721A__IERC721Receiver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ERC721A__IERC721Receiver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>>;
  export function getContractAt(
    contractName: "erc721a/contracts/ERC721A.sol:ERC721A__IERC721Receiver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721A__IERC721Receiver$Type["abi"]>>;
}
