/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collectionDeprecatedSol from "./Collection-deprecated.sol";
export type { collectionDeprecatedSol };
import type * as factoryDeprecatedSol from "./Factory-deprecated.sol";
export type { factoryDeprecatedSol };
import type * as spgnftCollectionSol from "./SPGNFTCollection.sol";
export type { spgnftCollectionSol };
import type * as stakingDeprecatedSol from "./Staking-deprecated.sol";
export type { stakingDeprecatedSol };
import type * as starglowTbaSol from "./StarglowTBA.sol";
export type { starglowTbaSol };
export type { Assets } from "./Assets";
export type { Raffles } from "./Raffles";
export type { SPGNFTFactory } from "./SPGNFTFactory";
