// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISPGNFT$Type } from "./ISPGNFT";
import { SPGNFTCollection$Type } from "./SPGNFTCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISPGNFT"]: ISPGNFT$Type;
    ["SPGNFTCollection"]: SPGNFTCollection$Type;
    ["contracts/SPGNFTCollection.sol:ISPGNFT"]: ISPGNFT$Type;
    ["contracts/SPGNFTCollection.sol:SPGNFTCollection"]: SPGNFTCollection$Type;
  }

  interface ContractTypesMap {
    ["ISPGNFT"]: GetContractReturnType<ISPGNFT$Type["abi"]>;
    ["SPGNFTCollection"]: GetContractReturnType<SPGNFTCollection$Type["abi"]>;
    ["contracts/SPGNFTCollection.sol:ISPGNFT"]: GetContractReturnType<ISPGNFT$Type["abi"]>;
    ["contracts/SPGNFTCollection.sol:SPGNFTCollection"]: GetContractReturnType<SPGNFTCollection$Type["abi"]>;
  }
}
