/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as collectionSol from "./Collection.sol";
export * as factorySol from "./Factory.sol";
export * as stakingSol from "./Staking.sol";
export { Assets__factory } from "./Assets__factory";
