/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as collectionDeprecatedSol from "./Collection-deprecated.sol";
export * as factoryDeprecatedSol from "./Factory-deprecated.sol";
export * as spgnftCollectionSol from "./SPGNFTCollection.sol";
export * as stakingDeprecatedSol from "./Staking-deprecated.sol";
export * as starglowTbaSol from "./StarglowTBA.sol";
export { Assets__factory } from "./Assets__factory";
export { Raffles__factory } from "./Raffles__factory";
export { SPGNFTFactory__factory } from "./SPGNFTFactory__factory";
