// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SlotDerivation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SlotDerivation",
  "sourceName": "@openzeppelin/contracts/utils/SlotDerivation.sol",
  "abi": [],
  "bytecode": "0x608060405234601a57604051603f6020823930815050603f90f35b600080fdfe6080604052600080fdfea2646970667358221220510e3335278aa6d2e57fd2371258e9e20e05febf3cb277ce64e44db94ab67f1f64736f6c634300081c0033",
  "deployedBytecode": "0x6080604052600080fdfea2646970667358221220510e3335278aa6d2e57fd2371258e9e20e05febf3cb277ce64e44db94ab67f1f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
}
