/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EIP712Domain,
  EIP712DomainInterface,
} from "../../../contracts/StarglowTBA.sol/EIP712Domain";

const _abi = [
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class EIP712Domain__factory {
  static readonly abi = _abi;
  static createInterface(): EIP712DomainInterface {
    return new Interface(_abi) as EIP712DomainInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EIP712Domain {
    return new Contract(address, _abi, runner) as unknown as EIP712Domain;
  }
}
