// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RafflesV2$Type } from "./RafflesV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RafflesV2"]: RafflesV2$Type;
    ["contracts/Raffles_v2.sol:RafflesV2"]: RafflesV2$Type;
  }

  interface ContractTypesMap {
    ["RafflesV2"]: GetContractReturnType<RafflesV2$Type["abi"]>;
    ["contracts/Raffles_v2.sol:RafflesV2"]: GetContractReturnType<RafflesV2$Type["abi"]>;
  }
}
