// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DeploySPGNFT$Type } from "./DeploySPGNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DeploySPGNFT"]: DeploySPGNFT$Type;
    ["contracts/DeploySPGNFT.sol:DeploySPGNFT"]: DeploySPGNFT$Type;
  }

  interface ContractTypesMap {
    ["DeploySPGNFT"]: GetContractReturnType<DeploySPGNFT$Type["abi"]>;
    ["contracts/DeploySPGNFT.sol:DeploySPGNFT"]: GetContractReturnType<DeploySPGNFT$Type["abi"]>;
  }
}
