// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Raffles$Type } from "./Raffles";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Raffles"]: Raffles$Type;
    ["contracts/Raffles.sol:Raffles"]: Raffles$Type;
  }

  interface ContractTypesMap {
    ["Raffles"]: GetContractReturnType<Raffles$Type["abi"]>;
    ["contracts/Raffles.sol:Raffles"]: GetContractReturnType<Raffles$Type["abi"]>;
  }
}
