// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EIP712Domain$Type } from "./EIP712Domain";
import { IERC6551Account$Type } from "./IERC6551Account";
import { StarglowTBA$Type } from "./StarglowTBA";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EIP712Domain"]: EIP712Domain$Type;
    ["IERC6551Account"]: IERC6551Account$Type;
    ["StarglowTBA"]: StarglowTBA$Type;
    ["contracts/StarglowTBA.sol:EIP712Domain"]: EIP712Domain$Type;
    ["contracts/StarglowTBA.sol:IERC6551Account"]: IERC6551Account$Type;
    ["contracts/StarglowTBA.sol:StarglowTBA"]: StarglowTBA$Type;
  }

  interface ContractTypesMap {
    ["EIP712Domain"]: GetContractReturnType<EIP712Domain$Type["abi"]>;
    ["IERC6551Account"]: GetContractReturnType<IERC6551Account$Type["abi"]>;
    ["StarglowTBA"]: GetContractReturnType<StarglowTBA$Type["abi"]>;
    ["contracts/StarglowTBA.sol:EIP712Domain"]: GetContractReturnType<EIP712Domain$Type["abi"]>;
    ["contracts/StarglowTBA.sol:IERC6551Account"]: GetContractReturnType<IERC6551Account$Type["abi"]>;
    ["contracts/StarglowTBA.sol:StarglowTBA"]: GetContractReturnType<StarglowTBA$Type["abi"]>;
  }
}
