/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
export { ERC1967Proxy__factory } from "./ERC1967Proxy__factory";
export { ERC1967Utils__factory } from "./ERC1967Utils__factory";
