"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC721Permit__factory = exports.Collection__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Collection__factory_1 = require("./Collection__factory");
Object.defineProperty(exports, "Collection__factory", { enumerable: true, get: function () { return Collection__factory_1.Collection__factory; } });
var IERC721Permit__factory_1 = require("./IERC721Permit__factory");
Object.defineProperty(exports, "IERC721Permit__factory", { enumerable: true, get: function () { return IERC721Permit__factory_1.IERC721Permit__factory; } });
