/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC6551Registry__factory } from "./IERC6551Registry__factory";
export { ISPGNFT__factory } from "./ISPGNFT__factory";
export { SPGNFTCollection__factory } from "./SPGNFTCollection__factory";
