/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISPGNFT,
  ISPGNFTInterface,
} from "../../../contracts/SPGNFTCollection.sol/ISPGNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISPGNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ISPGNFTInterface {
    return new Interface(_abi) as ISPGNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISPGNFT {
    return new Contract(address, _abi, runner) as unknown as ISPGNFT;
  }
}
