// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721AUpgradeable$Type } from "./ERC721AUpgradeable";
import { ERC721A__IERC721ReceiverUpgradeable$Type } from "./ERC721A__IERC721ReceiverUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721AUpgradeable"]: ERC721AUpgradeable$Type;
    ["ERC721A__IERC721ReceiverUpgradeable"]: ERC721A__IERC721ReceiverUpgradeable$Type;
    ["erc721a-upgradeable/contracts/ERC721AUpgradeable.sol:ERC721AUpgradeable"]: ERC721AUpgradeable$Type;
    ["erc721a-upgradeable/contracts/ERC721AUpgradeable.sol:ERC721A__IERC721ReceiverUpgradeable"]: ERC721A__IERC721ReceiverUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC721AUpgradeable"]: GetContractReturnType<ERC721AUpgradeable$Type["abi"]>;
    ["ERC721A__IERC721ReceiverUpgradeable"]: GetContractReturnType<ERC721A__IERC721ReceiverUpgradeable$Type["abi"]>;
    ["erc721a-upgradeable/contracts/ERC721AUpgradeable.sol:ERC721AUpgradeable"]: GetContractReturnType<ERC721AUpgradeable$Type["abi"]>;
    ["erc721a-upgradeable/contracts/ERC721AUpgradeable.sol:ERC721A__IERC721ReceiverUpgradeable"]: GetContractReturnType<ERC721A__IERC721ReceiverUpgradeable$Type["abi"]>;
  }
}
