// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Errors$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Errors",
  "sourceName": "@openzeppelin/contracts/utils/Errors.sol",
  "abi": [
    {
      "inputs": [],
      "name": "FailedCall",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "FailedDeployment",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "balance",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "needed",
          "type": "uint256"
        }
      ],
      "name": "InsufficientBalance",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "name": "MissingPrecompile",
      "type": "error"
    }
  ],
  "bytecode": "0x608060405234601a57604051603f6020823930815050603f90f35b600080fdfe6080604052600080fdfea2646970667358221220c05a0fa2f9f4e26c368efc45f278aee9cb0a8c1ca08939c7df3b01bb6724dbde64736f6c634300081c0033",
  "deployedBytecode": "0x6080604052600080fdfea2646970667358221220c05a0fa2f9f4e26c368efc45f278aee9cb0a8c1ca08939c7df3b01bb6724dbde64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
}
