// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721AStorage$Type } from "./ERC721AStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721AStorage"]: ERC721AStorage$Type;
    ["erc721a-upgradeable/contracts/ERC721AStorage.sol:ERC721AStorage"]: ERC721AStorage$Type;
  }

  interface ContractTypesMap {
    ["ERC721AStorage"]: GetContractReturnType<ERC721AStorage$Type["abi"]>;
    ["erc721a-upgradeable/contracts/ERC721AStorage.sol:ERC721AStorage"]: GetContractReturnType<ERC721AStorage$Type["abi"]>;
  }
}
