// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Assets$Type } from "./Assets";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Assets"]: Assets$Type;
    ["contracts/Assets.sol:Assets"]: Assets$Type;
  }

  interface ContractTypesMap {
    ["Assets"]: GetContractReturnType<Assets$Type["abi"]>;
    ["contracts/Assets.sol:Assets"]: GetContractReturnType<Assets$Type["abi"]>;
  }
}
