name: Update GitHub Wiki

on:
  push:
    branches:
      - main
    paths:
      - "wiki/**"

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout wiki repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: temp-wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy wiki files
        run: |
          cp -r wiki/* temp-wiki/

      - name: Commit and push changes
        working-directory: temp-wiki
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update wiki content"
          git push
