// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CollectionFactory$Type } from "./CollectionFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CollectionFactory"]: CollectionFactory$Type;
    ["contracts/Factory.sol:CollectionFactory"]: CollectionFactory$Type;
  }

  interface ContractTypesMap {
    ["CollectionFactory"]: GetContractReturnType<CollectionFactory$Type["abi"]>;
    ["contracts/Factory.sol:CollectionFactory"]: GetContractReturnType<CollectionFactory$Type["abi"]>;
  }
}
